using Trading.Core.Brokers;
using Trading.Core.FinancialValues;
using Trading.Core.Identifiers;
using Trading.Core.Policies;
using Trading.Core.Portfolios;

namespace Trading.Core.Tests.Portfolios;

[Category("PortfolioOrBrokerAggregates")]
public sealed class PortfolioBrokerAggregateTests
{
    private static readonly DateTimeOffset Now = new(2026, 8, 19, 12, 0, 0, TimeSpan.Zero);
    [Test] public void PortfolioEnforcesSingleBotCurrencyLockAndClosedState() { var p = NewPortfolio(); var bot = TradingBotId.New(); p.AssignTradingBot(bot); p.AssignTradingBot(bot); Assert.That(() => p.AssignTradingBot(TradingBotId.New()), Throws.InvalidOperationException); p.RecordCapitalChange(new Money(10, Currency.USD), "deposit-1"); Assert.That(() => p.ChangeBaseCurrency(Currency.EUR), Throws.InvalidOperationException); p.Close(); Assert.That(() => p.RecordCapitalChange(new Money(1, Currency.USD), "deposit-2"), Throws.InvalidOperationException); Assert.That(p.CanAcceptNewActivity, Is.False); }
    [Test] public void PositionRequiresAuditedSourceIsIdempotentAndCannotGoNegative() { var position = new Position(PositionId.New(), PortfolioId.New(), InstrumentId.New(), "shares", Currency.USD, Now); Assert.That(() => position.ApplyChange(1, new Money(10, Currency.USD), Money.Zero(Currency.USD), (PositionChangeSource)99, "x", Now), Throws.TypeOf<ArgumentOutOfRangeException>()); Assert.That(position.ApplyChange(2, new Money(10, Currency.USD), Money.Zero(Currency.USD), PositionChangeSource.Execution, "fill-1", Now), Is.True); Assert.That(position.ApplyChange(2, new Money(11, Currency.USD), Money.Zero(Currency.USD), PositionChangeSource.Execution, "fill-1", Now), Is.False); Assert.That(() => position.ApplyChange(-3, new Money(10, Currency.USD), Money.Zero(Currency.USD), PositionChangeSource.AuditedAdjustment, "adj-1", Now), Throws.InvalidOperationException); }
    [Test] public void SnapshotAndLedgerAreImmutable() { var positions = new List<PositionSnapshot> { new(InstrumentId.New(), 1, new Money(10, Currency.USD)) }; var snapshot = new PortfolioDecisionSnapshot(PortfolioDecisionSnapshotId.New(), PortfolioId.New(), TradingBotId.New(), TradingBotConfigurationVersionId.New(), Now, ReconciliationStatus.Reconciled, new Money(10, Currency.USD), new Money(10, Currency.USD), Money.Zero(Currency.USD), positions, [], 0, [], new DataFreshness(Now, Now, TimeSpan.FromMinutes(5)), Now); positions.Clear(); var ledger = new PortfolioLedgerEntry(PortfolioLedgerEntryId.New(), snapshot.PortfolioId, PortfolioLedgerEntryType.Deposit, new Money(10, Currency.USD), null, null, Now, LedgerSourceType.AuditedAdjustment, "deposit-1"); Assert.Multiple(() => { Assert.That(snapshot.PositionSnapshots, Has.Count.EqualTo(1)); Assert.That(typeof(PortfolioDecisionSnapshot).GetProperties().All(p => p.SetMethod is null), Is.True); Assert.That(typeof(PortfolioLedgerEntry).GetProperties().All(p => p.SetMethod is null), Is.True); Assert.That(ledger.SourceId, Is.EqualTo("deposit-1")); }); }
    [Test] public void BrokerEnvironmentAndAccountSafetyAreExplicit() { var paper = new BrokerConnection(BrokerConnectionId.New(), "sim", "Paper", BrokerEnvironment.Paper, "secret-ref", ["orders"], Now); var live = new BrokerConnection(BrokerConnectionId.New(), "sim", "Live", BrokerEnvironment.Live, "secret-ref", ["orders"], Now); Assert.That(paper.Environment, Is.Not.EqualTo(live.Environment)); Assert.That(() => paper.AuthorizeOperation(), Throws.InvalidOperationException); paper.Enable(); paper.AuthorizeOperation(); var account = new BrokerAccount(BrokerAccountId.New(), paper.Id, "A1", "Account", "Cash", Currency.USD); Assert.That(() => account.AuthorizeNewOrder(), Throws.InvalidOperationException); account.Reconcile(Now); account.AuthorizeNewOrder(); account.AssignPortfolio(PortfolioId.New()); Assert.That(() => account.AssignPortfolio(PortfolioId.New()), Throws.InvalidOperationException); }
    [Test] public void InstrumentIdentityIsStableAndMappingIntervalsCannotOverlap() { var connection = BrokerConnectionId.New(); var a = new Instrument(InstrumentId.New(), InstrumentType.Equity, "ABC", "Issuer A", Currency.USD, "NYSE"); var b = new Instrument(InstrumentId.New(), InstrumentType.Equity, "ABC", "Issuer B", Currency.USD, "NASDAQ"); Assert.That(a.Id, Is.Not.EqualTo(b.Id)); a.AddBrokerMapping(InstrumentBrokerMappingId.New(), connection, "one", "ABC", "NYSE", Now, Now.AddDays(10)); Assert.That(() => a.AddBrokerMapping(InstrumentBrokerMappingId.New(), connection, "two", "ABC2", "NYSE", Now.AddDays(9)), Throws.InvalidOperationException); a.AddBrokerMapping(InstrumentBrokerMappingId.New(), connection, "two", "ABC2", "NYSE", Now.AddDays(10)); Assert.That(a.Resolve(connection, Now.AddDays(10)).ExternalInstrumentId, Is.EqualTo("two")); }
    private static Portfolio NewPortfolio() => new(PortfolioId.New(), "Growth", Currency.USD, Money.Zero(Currency.USD), 10, Now);
}
