// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trading.Data;

#nullable disable

namespace Trading.Data.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260820164929_AddStage4ResearchPersistence")]
    partial class AddStage4ResearchPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Trading.Data.BotRunEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("AcceptedNextRunAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accepted_next_run_at");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at");

                    b.Property<string>("ConfigurationVersionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("configuration_version_id");

                    b.Property<string>("FinishStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("finish_status");

                    b.Property<string>("FinishSummary")
                        .HasColumnType("TEXT")
                        .HasColumnName("finish_summary");

                    b.Property<string>("InputRenderingHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("input_rendering_hash");

                    b.Property<string>("InputRenderingVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("input_rendering_version");

                    b.Property<long?>("LeaseExpiresAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("TEXT")
                        .HasColumnName("lease_owner");

                    b.Property<string>("ModelTranscriptJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model_transcript_json");

                    b.Property<int>("ModelTranscriptSchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_transcript_schema_version");

                    b.Property<string>("PortfolioSnapshotId")
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_snapshot_id");

                    b.Property<long?>("RequestedNextRunAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requested_next_run_at");

                    b.Property<string>("RequestedWakeReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_wake_reason");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TerminalReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("terminal_reason");

                    b.Property<string>("TradingBotId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trading_bot_id");

                    b.Property<string>("UsageJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("usage_json");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId");

                    b.HasIndex("PortfolioSnapshotId");

                    b.HasIndex("TradingBotId")
                        .IsUnique()
                        .HasFilter("status IN ('Pending', 'AcquiringLease', 'PreparingSnapshot', 'Reasoning', 'WaitingForTool')");

                    b.HasIndex("Status", "LeaseExpiresAt");

                    b.HasIndex("TradingBotId", "StartedAt")
                        .IsDescending(false, true);

                    b.ToTable("bot_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_bot_runs_completion", "(status IN ('Pending', 'AcquiringLease', 'PreparingSnapshot', 'Reasoning', 'WaitingForTool') AND completed_at IS NULL) OR (status IN ('Completed', 'TimedOut', 'BudgetExceeded', 'Cancelled', 'Faulted') AND completed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_bot_runs_lease", "(lease_owner IS NULL AND lease_expires_at IS NULL) OR (lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_bot_runs_rendering_version", "length(input_rendering_version) > 0");

                            t.HasCheckConstraint("ck_bot_runs_status", "status IN ('Pending', 'AcquiringLease', 'PreparingSnapshot', 'Reasoning', 'WaitingForTool', 'Completed', 'TimedOut', 'BudgetExceeded', 'Cancelled', 'Faulted')");

                            t.HasCheckConstraint("ck_bot_runs_transcript_schema", "model_transcript_schema_version > 0");

                            t.HasCheckConstraint("ck_bot_runs_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Trading.Data.BotRunTriggerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ConsumedByRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("consumed_by_run_id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<string>("TradingBotId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trading_bot_id");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_type");

                    b.HasKey("Id");

                    b.HasIndex("ConsumedByRunId");

                    b.HasIndex("TradingBotId", "ConsumedByRunId", "OccurredAt");

                    b.HasIndex("TradingBotId", "SourceType", "SourceId")
                        .IsUnique()
                        .HasFilter("source_id IS NOT NULL");

                    b.ToTable("bot_run_triggers", null, t =>
                        {
                            t.HasCheckConstraint("ck_bot_run_triggers_reason", "length(reason) > 0");

                            t.HasCheckConstraint("ck_bot_run_triggers_source", "(source_type IS NULL AND source_id IS NULL) OR (source_type IS NOT NULL AND source_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_bot_run_triggers_type", "trigger_type IN ('Manual', 'BaselineSchedule', 'AcceptedNextRun', 'ResearchCompleted', 'ResearchFailed', 'PortfolioEvent', 'RiskOrReconciliation')");
                        });
                });

            modelBuilder.Entity("Trading.Data.BotToolInvocationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("arguments_json");

                    b.Property<string>("BotRunId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bot_run_id");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_detail");

                    b.Property<string>("ResultArtifactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_artifact_id");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_json");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence_number");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_name");

                    b.Property<int>("ToolSchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tool_schema_version");

                    b.Property<string>("UsageJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("usage_json");

                    b.HasKey("Id");

                    b.HasIndex("BotRunId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("bot_tool_invocations", null, t =>
                        {
                            t.HasCheckConstraint("ck_bot_tool_invocations_completion", "(status = 'Started' AND completed_at IS NULL) OR (status IN ('Completed', 'Failed', 'Cancelled') AND completed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_bot_tool_invocations_schema", "tool_schema_version > 0");

                            t.HasCheckConstraint("ck_bot_tool_invocations_sequence", "sequence_number > 0");

                            t.HasCheckConstraint("ck_bot_tool_invocations_status", "status IN ('Started', 'Completed', 'Failed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("Trading.Data.BrokerAccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("account_type");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("base_currency");

                    b.Property<string>("BrokerConnectionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_connection_id");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("capabilities_json");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("external_account_id");

                    b.Property<long?>("LastReconciledAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_reconciled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("BrokerConnectionId", "ExternalAccountId")
                        .IsUnique();

                    b.ToTable("broker_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_broker_accounts_status", "status IN ('Active', 'Restricted', 'Disabled')");
                        });
                });

            modelBuilder.Entity("Trading.Data.BrokerConnectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BrokerType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_type");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("capabilities_json");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialReference")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("credential_reference");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("environment");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("broker_connections", null, t =>
                        {
                            t.HasCheckConstraint("ck_broker_connections_environment", "environment IN ('Paper', 'Live')");

                            t.HasCheckConstraint("ck_broker_connections_status", "status IN ('Enabled', 'Disabled', 'Disconnected')");
                        });
                });

            modelBuilder.Entity("Trading.Data.InstrumentBrokerMappingEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BrokerConnectionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_connection_id");

                    b.Property<long>("EffectiveFrom")
                        .HasColumnType("INTEGER")
                        .HasColumnName("effective_from");

                    b.Property<long?>("EffectiveTo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("effective_to");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("exchange");

                    b.Property<string>("ExternalInstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("external_instrument_id");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("BrokerConnectionId", "ExternalInstrumentId");

                    b.HasIndex("BrokerConnectionId", "ExternalInstrumentId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("instrument_broker_mappings", null, t =>
                        {
                            t.HasCheckConstraint("ck_instrument_broker_mappings_interval", "effective_to IS NULL OR effective_to > effective_from");
                        });
                });

            modelBuilder.Entity("Trading.Data.InstrumentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("exchange");

                    b.Property<string>("InstrumentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument_type");

                    b.Property<int>("PricePrecision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price_precision");

                    b.Property<string>("PrimarySymbol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("primary_symbol");

                    b.Property<int>("QuantityPrecision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity_precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentType", "PrimarySymbol", "Exchange")
                        .IsUnique();

                    b.ToTable("instruments", null, t =>
                        {
                            t.HasCheckConstraint("ck_instruments_price_precision", "price_precision BETWEEN 0 AND 8");

                            t.HasCheckConstraint("ck_instruments_quantity_precision", "quantity_precision BETWEEN 0 AND 8");

                            t.HasCheckConstraint("ck_instruments_status", "status IN ('Active', 'Inactive')");

                            t.HasCheckConstraint("ck_instruments_type", "instrument_type IN ('Equity', 'Option', 'Fund', 'Bond', 'Cash', 'Crypto')");
                        });
                });

            modelBuilder.Entity("Trading.Data.PortfolioDecisionSnapshotEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("AsOf")
                        .HasColumnType("INTEGER")
                        .HasColumnName("as_of");

                    b.Property<string>("ConfigurationVersionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("configuration_version_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("DataFreshnessJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data_freshness_json");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("ReconciliationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reconciliation_status");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_json");

                    b.Property<int>("SnapshotSchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("snapshot_schema_version");

                    b.Property<string>("TradingBotId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trading_bot_id");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId");

                    b.HasIndex("PortfolioId", "AsOf")
                        .IsDescending(false, true);

                    b.HasIndex("TradingBotId", "AsOf")
                        .IsDescending(false, true);

                    b.ToTable("portfolio_decision_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolio_decision_snapshots_hash", "length(content_hash) = 64 AND content_hash = lower(content_hash)");

                            t.HasCheckConstraint("ck_portfolio_decision_snapshots_reconciliation_status", "reconciliation_status IN ('Reconciled', 'Pending', 'Uncertain')");

                            t.HasCheckConstraint("ck_portfolio_decision_snapshots_schema_version", "snapshot_schema_version > 0");
                        });
                });

            modelBuilder.Entity("Trading.Data.PortfolioEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AssignedTradingBotId")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_trading_bot_id");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("base_currency");

                    b.Property<string>("BrokerAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_account_id");

                    b.Property<string>("CapitalAllocationAmount")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("capital_allocation_amount");

                    b.Property<string>("CashReservePolicyJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cash_reserve_policy_json");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTradingBotId")
                        .IsUnique()
                        .HasFilter("assigned_trading_bot_id IS NOT NULL AND status = 'Active'");

                    b.HasIndex("BrokerAccountId")
                        .IsUnique()
                        .HasFilter("broker_account_id IS NOT NULL AND status = 'Active'");

                    b.ToTable("portfolios", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolios_status", "status IN ('Active', 'Paused', 'Closed')");
                        });
                });

            modelBuilder.Entity("Trading.Data.PortfolioLedgerEntryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Amount")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<long>("EffectiveAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("effective_at");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_type");

                    b.Property<string>("InstrumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument_id");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("Quantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<long>("RecordedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recorded_at");

                    b.Property<string>("ReversesEntryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reverses_entry_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("ReversesEntryId");

                    b.HasIndex("PortfolioId", "EffectiveAt");

                    b.HasIndex("PortfolioId", "SourceType", "SourceId")
                        .IsUnique();

                    b.ToTable("portfolio_ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolio_ledger_entries_source_type", "source_type IN ('BrokerExecution', 'BrokerEvent', 'AuditedAdjustment')");

                            t.HasCheckConstraint("ck_portfolio_ledger_entries_type", "entry_type IN ('Deposit', 'Withdrawal', 'Settlement', 'Fee', 'Dividend', 'Interest', 'Tax', 'CorporateAction', 'ManualCorrection')");
                        });
                });

            modelBuilder.Entity("Trading.Data.PositionAppliedFillEntity", b =>
                {
                    b.Property<string>("PositionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("position_id");

                    b.Property<string>("FillId")
                        .HasColumnType("TEXT")
                        .HasColumnName("fill_id");

                    b.Property<long>("AppliedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("applied_at");

                    b.HasKey("PositionId", "FillId");

                    b.ToTable("position_applied_fills", (string)null);
                });

            modelBuilder.Entity("Trading.Data.PositionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AverageCostAmount")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("average_cost_amount");

                    b.Property<string>("AverageCostCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("average_cost_currency");

                    b.Property<long?>("ClosedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("closed_at");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument_id");

                    b.Property<long>("OpenedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("opened_at");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity_unit");

                    b.Property<string>("RealizedPnlAmount")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("realized_pnl_amount");

                    b.Property<string>("RealizedPnlCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("realized_pnl_currency");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PortfolioId", "InstrumentId")
                        .IsUnique();

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("Trading.Data.ResearchReportEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_json");

                    b.Property<string>("ContentMarkdown")
                        .HasColumnType("TEXT")
                        .HasColumnName("content_markdown");

                    b.Property<long>("DataCutoff")
                        .HasColumnType("INTEGER")
                        .HasColumnName("data_cutoff");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_at");

                    b.Property<long>("GeneratedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generated_at");

                    b.Property<string>("GeneratorMetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("generator_metadata_json");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("question");

                    b.Property<string>("ReportSchemaVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("report_schema_version");

                    b.Property<string>("ReportSeriesId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("report_series_id");

                    b.Property<string>("ResearchRequestId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("research_request_id");

                    b.Property<string>("ResearchRunId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("research_run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_type");

                    b.Property<string>("SupersedesReportId")
                        .HasColumnType("TEXT")
                        .HasColumnName("supersedes_report_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_number");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("ResearchRequestId");

                    b.HasIndex("ResearchRunId");

                    b.HasIndex("SupersedesReportId");

                    b.HasIndex("ReportSeriesId", "ContentHash")
                        .IsUnique();

                    b.HasIndex("ReportSeriesId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("SubjectId", "GeneratedAt")
                        .IsDescending(false, true);

                    b.ToTable("research_reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_research_reports_hash", "length(content_hash) = 64 AND content_hash = lower(content_hash)");

                            t.HasCheckConstraint("ck_research_reports_status", "status IN ('Published','Expired','Superseded','Retracted')");

                            t.HasCheckConstraint("ck_research_reports_version", "version_number > 0");

                            t.HasCheckConstraint("ck_research_reports_visibility", "visibility IN ('Shared','BotPrivate','Restricted')");
                        });
                });

            modelBuilder.Entity("Trading.Data.ResearchReportSourceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<long?>("PublishedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("published_at");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT")
                        .HasColumnName("publisher");

                    b.Property<string>("ResearchReportId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("research_report_id");

                    b.Property<long>("RetrievedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retrieved_at");

                    b.Property<int>("SourceSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_sequence");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<string>("SourceUri")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_uri");

                    b.Property<string>("StableSourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("stable_source_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ResearchReportId", "SourceSequence")
                        .IsUnique();

                    b.ToTable("research_report_sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_research_report_sources_hash", "length(content_hash) = 64 AND content_hash = lower(content_hash)");

                            t.HasCheckConstraint("ck_research_report_sources_sequence", "source_sequence > 0");
                        });
                });

            modelBuilder.Entity("Trading.Data.ResearchRequestEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("AsOf")
                        .HasColumnType("INTEGER")
                        .HasColumnName("as_of");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("FreshnessRequirementJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("freshness_requirement_json");

                    b.Property<string>("NormalizedResearchKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_research_key");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("question");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("request_json");

                    b.Property<string>("RequestingBotId")
                        .HasColumnType("TEXT")
                        .HasColumnName("requesting_bot_id");

                    b.Property<string>("ResultReportId")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_report_id");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_type");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("RequestingBotId");

                    b.HasIndex("ResultReportId");

                    b.HasIndex("NormalizedResearchKey", "Status");

                    b.ToTable("research_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_research_requests_status", "status IN ('Requested','Validating','Queued','Running','Completed','Failed','TimedOut','BudgetExceeded','Cancelled')");

                            t.HasCheckConstraint("ck_research_requests_version", "version > 0");

                            t.HasCheckConstraint("ck_research_requests_visibility", "visibility IN ('Shared','BotPrivate','Restricted')");
                        });
                });

            modelBuilder.Entity("Trading.Data.ResearchRunEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_number");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at");

                    b.Property<string>("ModelConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model_configuration_json");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_version");

                    b.Property<string>("ReportSchemaVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("report_schema_version");

                    b.Property<string>("ResearchRequestId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("research_request_id");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TerminalReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("terminal_reason");

                    b.Property<string>("ToolSetVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_set_version");

                    b.Property<string>("UsageJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("usage_json");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ResearchRequestId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("research_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_research_runs_attempt", "attempt_number > 0");

                            t.HasCheckConstraint("ck_research_runs_status", "status IN ('Pending','Running','WaitingForTool','Completed','Failed','TimedOut','BudgetExceeded','Cancelled')");

                            t.HasCheckConstraint("ck_research_runs_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Trading.Data.ResearchSubscriptionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("NotificationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("notification_status");

                    b.Property<long?>("NotifiedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("notified_at");

                    b.Property<string>("ResearchRequestId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("research_request_id");

                    b.Property<long>("SubscribedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subscribed_at");

                    b.Property<string>("TradingBotId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trading_bot_id");

                    b.HasKey("Id");

                    b.HasIndex("TradingBotId");

                    b.HasIndex("ResearchRequestId", "TradingBotId")
                        .IsUnique();

                    b.ToTable("research_subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_research_subscriptions_notification", "notification_status IN ('Pending','Delivered','Failed')");
                        });
                });

            modelBuilder.Entity("Trading.Data.ResearchToolInvocationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("arguments_json");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_detail");

                    b.Property<string>("ResearchRunId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("research_run_id");

                    b.Property<string>("ResultArtifactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_artifact_id");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_json");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence_number");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_name");

                    b.Property<int>("ToolSchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tool_schema_version");

                    b.Property<string>("UsageJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("usage_json");

                    b.HasKey("Id");

                    b.HasIndex("ResearchRunId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("research_tool_invocations", null, t =>
                        {
                            t.HasCheckConstraint("ck_research_tool_invocations_schema", "tool_schema_version > 0");

                            t.HasCheckConstraint("ck_research_tool_invocations_sequence", "sequence_number > 0");

                            t.HasCheckConstraint("ck_research_tool_invocations_status", "status IN ('Started','Succeeded','Failed','Rejected','Cancelled')");
                        });
                });

            modelBuilder.Entity("Trading.Data.SchemaMetadataEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("schema_metadata", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "application_data_format_version",
                            UpdatedAt = 0L,
                            Value = "4"
                        });
                });

            modelBuilder.Entity("Trading.Data.TradingBotConfigurationVersionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("ActivatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activated_at");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_mode");

                    b.Property<string>("InvestmentMandateJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("investment_mandate_json");

                    b.Property<string>("ModelConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model_configuration_json");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_version");

                    b.Property<string>("RiskPolicyJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("risk_policy_json");

                    b.Property<string>("RunBudgetJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_budget_json");

                    b.Property<string>("SchedulingPolicyJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduling_policy_json");

                    b.Property<long?>("SupersededAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("superseded_at");

                    b.Property<string>("ToolPolicyJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_policy_json");

                    b.Property<string>("TradingBotId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trading_bot_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("TradingBotId", "ContentHash")
                        .IsUnique();

                    b.HasIndex("TradingBotId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("trading_bot_configuration_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_trading_bot_configuration_versions_execution_mode", "execution_mode IN ('ResearchOnly', 'HumanApproval', 'PaperTrading', 'LiveTrading')");

                            t.HasCheckConstraint("ck_trading_bot_configuration_versions_hash", "length(content_hash) = 64 AND content_hash = lower(content_hash)");

                            t.HasCheckConstraint("ck_trading_bot_configuration_versions_number", "version_number > 0");
                        });
                });

            modelBuilder.Entity("Trading.Data.TradingBotEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("AcceptedNextRunAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accepted_next_run_at");

                    b.Property<string>("ActiveConfigurationVersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("active_configuration_version_id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("LastCompletedRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_completed_run_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long?>("RequestedNextRunAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requested_next_run_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ActiveConfigurationVersionId");

                    b.HasIndex("LastCompletedRunId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status", "AcceptedNextRunAt");

                    b.ToTable("trading_bots", null, t =>
                        {
                            t.HasCheckConstraint("ck_trading_bots_status", "status IN ('Enabled', 'Paused', 'Retired')");
                        });
                });

            modelBuilder.Entity("Trading.Data.BotRunEntity", b =>
                {
                    b.HasOne("Trading.Data.TradingBotConfigurationVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Data.PortfolioDecisionSnapshotEntity", null)
                        .WithMany()
                        .HasForeignKey("PortfolioSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Trading.Data.TradingBotEntity", null)
                        .WithMany()
                        .HasForeignKey("TradingBotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.BotRunTriggerEntity", b =>
                {
                    b.HasOne("Trading.Data.BotRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ConsumedByRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Trading.Data.TradingBotEntity", null)
                        .WithMany()
                        .HasForeignKey("TradingBotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.BotToolInvocationEntity", b =>
                {
                    b.HasOne("Trading.Data.BotRunEntity", null)
                        .WithMany()
                        .HasForeignKey("BotRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.BrokerAccountEntity", b =>
                {
                    b.HasOne("Trading.Data.BrokerConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.InstrumentBrokerMappingEntity", b =>
                {
                    b.HasOne("Trading.Data.BrokerConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Data.InstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.PortfolioDecisionSnapshotEntity", b =>
                {
                    b.HasOne("Trading.Data.TradingBotConfigurationVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Data.PortfolioEntity", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Data.TradingBotEntity", null)
                        .WithMany()
                        .HasForeignKey("TradingBotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.PortfolioEntity", b =>
                {
                    b.HasOne("Trading.Data.TradingBotEntity", null)
                        .WithMany()
                        .HasForeignKey("AssignedTradingBotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Trading.Data.BrokerAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Trading.Data.PortfolioLedgerEntryEntity", b =>
                {
                    b.HasOne("Trading.Data.InstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Trading.Data.PortfolioEntity", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Data.PortfolioLedgerEntryEntity", null)
                        .WithMany()
                        .HasForeignKey("ReversesEntryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Trading.Data.PositionAppliedFillEntity", b =>
                {
                    b.HasOne("Trading.Data.PositionEntity", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.PositionEntity", b =>
                {
                    b.HasOne("Trading.Data.InstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Data.PortfolioEntity", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.ResearchReportEntity", b =>
                {
                    b.HasOne("Trading.Data.ResearchRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("ResearchRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Data.ResearchRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Data.ResearchReportEntity", null)
                        .WithMany()
                        .HasForeignKey("SupersedesReportId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Trading.Data.ResearchReportSourceEntity", b =>
                {
                    b.HasOne("Trading.Data.ResearchReportEntity", null)
                        .WithMany()
                        .HasForeignKey("ResearchReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.ResearchRequestEntity", b =>
                {
                    b.HasOne("Trading.Data.TradingBotEntity", null)
                        .WithMany()
                        .HasForeignKey("RequestingBotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Trading.Data.ResearchReportEntity", null)
                        .WithMany()
                        .HasForeignKey("ResultReportId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Trading.Data.ResearchRunEntity", b =>
                {
                    b.HasOne("Trading.Data.ResearchRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("ResearchRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.ResearchSubscriptionEntity", b =>
                {
                    b.HasOne("Trading.Data.ResearchRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("ResearchRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Data.TradingBotEntity", null)
                        .WithMany()
                        .HasForeignKey("TradingBotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.ResearchToolInvocationEntity", b =>
                {
                    b.HasOne("Trading.Data.ResearchRunEntity", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.TradingBotConfigurationVersionEntity", b =>
                {
                    b.HasOne("Trading.Data.TradingBotEntity", null)
                        .WithMany()
                        .HasForeignKey("TradingBotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.TradingBotEntity", b =>
                {
                    b.HasOne("Trading.Data.TradingBotConfigurationVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("ActiveConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Trading.Data.BotRunEntity", null)
                        .WithMany()
                        .HasForeignKey("LastCompletedRunId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
