// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trading.Data;

#nullable disable

namespace Trading.Data.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    partial class TradingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Trading.Data.BrokerAccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("account_type");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("base_currency");

                    b.Property<string>("BrokerConnectionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_connection_id");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("capabilities_json");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("external_account_id");

                    b.Property<long?>("LastReconciledAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_reconciled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("BrokerConnectionId", "ExternalAccountId")
                        .IsUnique();

                    b.ToTable("broker_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_broker_accounts_status", "status IN ('Active', 'Restricted', 'Disabled')");
                        });
                });

            modelBuilder.Entity("Trading.Data.BrokerConnectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BrokerType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_type");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("capabilities_json");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialReference")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("credential_reference");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("environment");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("broker_connections", null, t =>
                        {
                            t.HasCheckConstraint("ck_broker_connections_environment", "environment IN ('Paper', 'Live')");

                            t.HasCheckConstraint("ck_broker_connections_status", "status IN ('Enabled', 'Disabled', 'Disconnected')");
                        });
                });

            modelBuilder.Entity("Trading.Data.InstrumentBrokerMappingEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BrokerConnectionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_connection_id");

                    b.Property<long>("EffectiveFrom")
                        .HasColumnType("INTEGER")
                        .HasColumnName("effective_from");

                    b.Property<long?>("EffectiveTo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("effective_to");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("exchange");

                    b.Property<string>("ExternalInstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("external_instrument_id");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("BrokerConnectionId", "ExternalInstrumentId");

                    b.HasIndex("BrokerConnectionId", "ExternalInstrumentId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("instrument_broker_mappings", null, t =>
                        {
                            t.HasCheckConstraint("ck_instrument_broker_mappings_interval", "effective_to IS NULL OR effective_to > effective_from");
                        });
                });

            modelBuilder.Entity("Trading.Data.InstrumentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("exchange");

                    b.Property<string>("InstrumentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument_type");

                    b.Property<int>("PricePrecision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price_precision");

                    b.Property<string>("PrimarySymbol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("primary_symbol");

                    b.Property<int>("QuantityPrecision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity_precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentType", "PrimarySymbol", "Exchange")
                        .IsUnique();

                    b.ToTable("instruments", null, t =>
                        {
                            t.HasCheckConstraint("ck_instruments_price_precision", "price_precision BETWEEN 0 AND 8");

                            t.HasCheckConstraint("ck_instruments_quantity_precision", "quantity_precision BETWEEN 0 AND 8");

                            t.HasCheckConstraint("ck_instruments_status", "status IN ('Active', 'Inactive')");

                            t.HasCheckConstraint("ck_instruments_type", "instrument_type IN ('Equity', 'Option', 'Fund', 'Bond', 'Cash', 'Crypto')");
                        });
                });

            modelBuilder.Entity("Trading.Data.PortfolioDecisionSnapshotEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("AsOf")
                        .HasColumnType("INTEGER")
                        .HasColumnName("as_of");

                    b.Property<string>("ConfigurationVersionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("configuration_version_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("DataFreshnessJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data_freshness_json");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("ReconciliationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reconciliation_status");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_json");

                    b.Property<int>("SnapshotSchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("snapshot_schema_version");

                    b.Property<string>("TradingBotId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trading_bot_id");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId");

                    b.HasIndex("PortfolioId", "AsOf")
                        .IsDescending(false, true);

                    b.HasIndex("TradingBotId", "AsOf")
                        .IsDescending(false, true);

                    b.ToTable("portfolio_decision_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolio_decision_snapshots_hash", "length(content_hash) = 64 AND content_hash = lower(content_hash)");

                            t.HasCheckConstraint("ck_portfolio_decision_snapshots_reconciliation_status", "reconciliation_status IN ('Reconciled', 'Pending', 'Uncertain')");

                            t.HasCheckConstraint("ck_portfolio_decision_snapshots_schema_version", "snapshot_schema_version > 0");
                        });
                });

            modelBuilder.Entity("Trading.Data.PortfolioEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AssignedTradingBotId")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_trading_bot_id");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("base_currency");

                    b.Property<string>("BrokerAccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("broker_account_id");

                    b.Property<string>("CapitalAllocationAmount")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("capital_allocation_amount");

                    b.Property<string>("CashReservePolicyJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cash_reserve_policy_json");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTradingBotId")
                        .IsUnique()
                        .HasFilter("assigned_trading_bot_id IS NOT NULL AND status = 'Active'");

                    b.HasIndex("BrokerAccountId")
                        .IsUnique()
                        .HasFilter("broker_account_id IS NOT NULL AND status = 'Active'");

                    b.ToTable("portfolios", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolios_status", "status IN ('Active', 'Paused', 'Closed')");
                        });
                });

            modelBuilder.Entity("Trading.Data.PortfolioLedgerEntryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Amount")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<long>("EffectiveAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("effective_at");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_type");

                    b.Property<string>("InstrumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument_id");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("Quantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<long>("RecordedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recorded_at");

                    b.Property<string>("ReversesEntryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("reverses_entry_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("ReversesEntryId");

                    b.HasIndex("PortfolioId", "EffectiveAt");

                    b.HasIndex("PortfolioId", "SourceType", "SourceId")
                        .IsUnique();

                    b.ToTable("portfolio_ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolio_ledger_entries_source_type", "source_type IN ('BrokerExecution', 'BrokerEvent', 'AuditedAdjustment')");

                            t.HasCheckConstraint("ck_portfolio_ledger_entries_type", "entry_type IN ('Deposit', 'Withdrawal', 'Settlement', 'Fee', 'Dividend', 'Interest', 'Tax', 'CorporateAction', 'ManualCorrection')");
                        });
                });

            modelBuilder.Entity("Trading.Data.PositionAppliedFillEntity", b =>
                {
                    b.Property<string>("PositionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("position_id");

                    b.Property<string>("FillId")
                        .HasColumnType("TEXT")
                        .HasColumnName("fill_id");

                    b.Property<long>("AppliedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("applied_at");

                    b.HasKey("PositionId", "FillId");

                    b.ToTable("position_applied_fills", (string)null);
                });

            modelBuilder.Entity("Trading.Data.PositionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AverageCostAmount")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("average_cost_amount");

                    b.Property<string>("AverageCostCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("average_cost_currency");

                    b.Property<long?>("ClosedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("closed_at");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instrument_id");

                    b.Property<long>("OpenedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("opened_at");

                    b.Property<string>("PortfolioId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity_unit");

                    b.Property<string>("RealizedPnlAmount")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("realized_pnl_amount");

                    b.Property<string>("RealizedPnlCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("realized_pnl_currency");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PortfolioId", "InstrumentId")
                        .IsUnique();

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("Trading.Data.SchemaMetadataEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("schema_metadata", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "application_data_format_version",
                            UpdatedAt = 0L,
                            Value = "2"
                        });
                });

            modelBuilder.Entity("Trading.Data.TradingBotConfigurationVersionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("ActivatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activated_at");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_mode");

                    b.Property<string>("InvestmentMandateJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("investment_mandate_json");

                    b.Property<string>("ModelConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model_configuration_json");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_version");

                    b.Property<string>("RiskPolicyJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("risk_policy_json");

                    b.Property<string>("RunBudgetJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_budget_json");

                    b.Property<string>("SchedulingPolicyJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduling_policy_json");

                    b.Property<long?>("SupersededAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("superseded_at");

                    b.Property<string>("ToolPolicyJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_policy_json");

                    b.Property<string>("TradingBotId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trading_bot_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("TradingBotId", "ContentHash")
                        .IsUnique();

                    b.HasIndex("TradingBotId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("trading_bot_configuration_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_trading_bot_configuration_versions_execution_mode", "execution_mode IN ('ResearchOnly', 'HumanApproval', 'PaperTrading', 'LiveTrading')");

                            t.HasCheckConstraint("ck_trading_bot_configuration_versions_hash", "length(content_hash) = 64 AND content_hash = lower(content_hash)");

                            t.HasCheckConstraint("ck_trading_bot_configuration_versions_number", "version_number > 0");
                        });
                });

            modelBuilder.Entity("Trading.Data.TradingBotEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("AcceptedNextRunAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accepted_next_run_at");

                    b.Property<string>("ActiveConfigurationVersionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("active_configuration_version_id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("LastCompletedRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_completed_run_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long?>("RequestedNextRunAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requested_next_run_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ActiveConfigurationVersionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status", "AcceptedNextRunAt");

                    b.ToTable("trading_bots", null, t =>
                        {
                            t.HasCheckConstraint("ck_trading_bots_status", "status IN ('Enabled', 'Paused', 'Retired')");
                        });
                });

            modelBuilder.Entity("Trading.Data.BrokerAccountEntity", b =>
                {
                    b.HasOne("Trading.Data.BrokerConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.InstrumentBrokerMappingEntity", b =>
                {
                    b.HasOne("Trading.Data.BrokerConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Data.InstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.PortfolioDecisionSnapshotEntity", b =>
                {
                    b.HasOne("Trading.Data.TradingBotConfigurationVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Data.PortfolioEntity", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Data.TradingBotEntity", null)
                        .WithMany()
                        .HasForeignKey("TradingBotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.PortfolioEntity", b =>
                {
                    b.HasOne("Trading.Data.TradingBotEntity", null)
                        .WithMany()
                        .HasForeignKey("AssignedTradingBotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Trading.Data.BrokerAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("BrokerAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Trading.Data.PortfolioLedgerEntryEntity", b =>
                {
                    b.HasOne("Trading.Data.InstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Trading.Data.PortfolioEntity", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Data.PortfolioLedgerEntryEntity", null)
                        .WithMany()
                        .HasForeignKey("ReversesEntryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Trading.Data.PositionAppliedFillEntity", b =>
                {
                    b.HasOne("Trading.Data.PositionEntity", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.PositionEntity", b =>
                {
                    b.HasOne("Trading.Data.InstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Data.PortfolioEntity", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.TradingBotConfigurationVersionEntity", b =>
                {
                    b.HasOne("Trading.Data.TradingBotEntity", null)
                        .WithMany()
                        .HasForeignKey("TradingBotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Data.TradingBotEntity", b =>
                {
                    b.HasOne("Trading.Data.TradingBotConfigurationVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("ActiveConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
