<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Trading.Brokers\Trading.Brokers.csproj" />
    <ProjectReference Include="..\Trading.Core\Trading.Core.csproj" />
    <ProjectReference Include="..\Trading.Data\Trading.Data.csproj" />
    <ProjectReference Include="..\Trading.Engine\Trading.Engine.csproj" />
    <ProjectReference Include="..\Trading.Research\Trading.Research.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
</Project>
